language: node_js
node_js:
  - "6"
cache: yarn
before_script:
  - "npm run lint"
script:
  - "npm run test-ci"
  - "yarn global add codeclimate-test-reporter"
  - "codeclimate-test-reporter < ./coverage/lcov.info"
before_deploy:
  - echo -e $PROD_ENV > .env
addons:
  code_climate:
    repo_token: a4e4ca16789d6c0af6f80b9119febb6e385a3bfe437ed5f28a10c84e05789961
