language: node_js
node_js:
  - "6"
cache: yarn
before_script:
  - "npm run lint"
script:
  - "npm run test-ci"
  - "yarn global add codeclimate-test-reporter"
  - "codeclimate-test-reporter < ./coverage/lcov.info"
